---
- hosts: all
  gather_facts: false

  tasks:
    - name: Wait until SSH is available
      local_action: 
        module: wait_for 
        host: "{{ ansible_ssh_host }}"
        port: 22
        state: started
      retries: 30
      delay: 10

    # The following task is just to ensure our Python bootstrapper doesn't
    # fail. The real apt-get cache with cache validity timeout appears
    # further down this playbook.
    - name: Update apt-get cache
      become: true
      raw: "apt-get -y -q update && touch ~/.run_once_cache_update"
      args:
        creates: ~/.run_once_cache_update
      retries: 10
      delay: 10

    - name: Check if Python is installed
      command: which python
      register: python_check
      changed_when: false
      ignore_errors: true

    - name: Install Python
      when: python_check | failed
      raw: "apt-get -y -q install python"
      retries: 3
      become: true

    - name: Check if pip is installed
      command: which pip
      register: pip_check
      changed_when: false
      ignore_errors: true

    - name: Install pip
      when: pip_check | failed
      raw: "apt-get -y -q install python-pip"
      retries: 3
      become: true

    - name: Update apt-get cache
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 604800

- hosts: jumpbox
  roles:
    - jumpbox

    - role: rvm_io.ruby
      become: yes
      rvm1_rubies:
        - 'ruby-2.3.3'
      rvm1_user: 'root'
      rvm1_install_flags: '--auto-dotfiles'
      rvm1_install_path: /usr/local/rvm

    - role: ansible-go
      become: yes
      go_tarball: go1.7.4.linux-amd64.tar.gz
      go_tarball_checksum: sha256:47fda42e46b4c3ec93fa5d4d4cc6a748aa3f9411a2a2b7e08e3a6d80d753ec8b
      go_version_target: 'go version go1.7.4 linux/amd64'

    - dotfiles
